spring.application.name=leave-portal-app
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

oci.region=${OCI_REGION:us-ashburn-1}
oci.namespace=${OCI_NAMESPACE:idqag2xakgns}
oci.bucket-name=${OCI_BUCKET_NAME:sick-leaves-bucket}
oci.config-file=${OCI_CONFIG_FILE:C:/Users/mahmo/Desktop/.oci/config}
oci.profile=${OCI_PROFILE:DEFAULT}
