plugins {
	id 'java'
	id 'application'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.agileoracles'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

application {
	mainClass = project.hasProperty('mainClass') ? project.getProperty('mainClass') : 'com.agileoracles.leave_portal_app.LeavePortalAppApplication'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.oracle.database.jdbc:ojdbc11:23.26.2.0.0'
	implementation 'org.apache.pdfbox:pdfbox:3.0.8'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'com.oracle.oci.sdk:oci-java-sdk-objectstorage:3.94.0'
	implementation 'com.oracle.oci.sdk:oci-java-sdk-common-httpclient-jersey3:3.94.0'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}